# Generated by Django 5.1.4 on 2024-12-10 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='game_thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_scores', to='games.game')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_scores', to='profiles.profile')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('profile', 'game')},
            },
        ),
    ]
